Repository LdDl/ch, pull requests merged in 2022-09, with the labels that each got.

#26 Add vertex alternatives support
  bidirectional_ch_test.go
  dijkstra_bidirectional.go
Labels: enhancement, good first issue

#29 Add dead simple graph gen + adjust one of benches
  .gitignore
  BENCHMARK.md
  bench_187k_vertices.txt
  bidirectional_ch_one_to_n_test.go
  bidirectional_ch_test.go
  new.txt
  old.txt
Labels: bug

#31 Add alternatives support for ShortestPathOneToMany
  bidirectional_ch_one_to_n.go
Labels: enhancement

#32 Unify vertex heaps
  bidirectional_ch_one_to_n.go
  dijkstra_bidirectional.go
  heap_backward.go
  heap_dist.go
  heap_forward.go
Labels: enhancement, help wanted

#30 Implement ShortestPathManyToMany
  bidirectional_ch_n_to_n.go
  bidirectional_ch_n_to_n_test.go
  dijkstra_bidirectional.go
Labels: enhancement, review

#33 Unify forward and backward search
  dijkstra_bidirectional.go
Labels: enhancement, review
